name: .NET

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - id: get_version
      uses: battila7/get-version-action@v2
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: "src/Row Counter/Row Counter.csproj"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.get_version.outputs.version }}
